USE [SocialMediaClean]

CREATE TABLE Users(
ID INT IDENTITY PRIMARY KEY,
Email VARCHAR(255) NOT NULL UNIQUE,
Password VARCHAR(MAX),
PasswordSalt VARCHAR(MAX),
PhoneNumber VARCHAR(15),
JoinedAt DATETIME DEFAULT GETDATE(),
BirthDay DATETIME,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Gender VARCHAR(2),
Country VARCHAR(50),
City VARCHAR(50),
Address VARCHAR(75),
ProfilePictureURL VARCHAR(MAX),
CoverPictureURL VARCHAR(MAX),
PasswordForgotToken VARCHAR(MAX),
PasswordChangeToken VARCHAR(MAX),
EmailVerified BIT NOT NULL DEFAULT 0,
EmailVerifyToken VARCHAR(MAX)
);

CREATE UNIQUE NONCLUSTERED INDEX id1_phoneNumber_notnull
ON Users(PhoneNumber)
WHERE PhoneNumber IS NOT NULL;


CREATE TABLE LogEntries (
    Id INT PRIMARY KEY IDENTITY,
    Message NVARCHAR(MAX),
    LogLevel NVARCHAR(50),
    Timestamp DATETIME DEFAULT GETDATE()
);

CREATE TABLE Groups(
ID INT IDENTITY PRIMARY KEY,
AuthorID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
Name NVARCHAR(50) NOT NULL,
Description NVARCHAR(MAX),
CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE Statuses(
ID INT IDENTITY PRIMARY KEY,
Status NVARCHAR(MAX) NOT NULL,
)

CREATE TABLE Posts(
ID INT IDENTITY PRIMARY KEY,
AuthorID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
SharedByID INT FOREIGN KEY REFERENCES Users(ID) DEFAULT NULL,
StatusID INT FOREIGN KEY REFERENCES Statuses(ID) DEFAULT 1,
GroupID INT FOREIGN KEY REFERENCES Groups(ID) DEFAULT NULL,
Body NVARCHAR(MAX) NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE Pictures(
ID INT IDENTITY PRIMARY KEY,
PostID INT FOREIGN KEY REFERENCES Posts(ID),
PictureURI NVARCHAR(MAX) NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE Videos(
ID INT IDENTITY PRIMARY KEY,
PostID INT FOREIGN KEY REFERENCES Posts(ID),
VideoURI NVARCHAR(MAX) NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);

INSERT INTO Statuses(Status) VALUES('Public');
INSERT INTO Statuses(Status) VALUES('Friends');
INSERT INTO Statuses(Status) VALUES('OnlyMe');

CREATE TABLE Recipe(
ID INT IDENTITY PRIMARY KEY,
PostID INT FOREIGN KEY REFERENCES Posts(ID),
Name NVARCHAR(50) NOT NULL,
Description NVARCHAR(255) NOT NULL,
Instructions NVARCHAR(511) NOT NULL,
CookingTime INT NOT NULL,
Servings INT NOT NULL,
Calories INT NOT NULL,
Protein INT NOT NULL,
Carbs INT NOT NULL,
Fat INT NOT NULL,
);

CREATE TABLE Ingredients(
ID INT IDENTITY PRIMARY KEY,
RecipeID INT FOREIGN KEY REFERENCES Recipe(ID),
Name NVARCHAR(50) NOT NULL,
Quantity INT NOT NULL,
Unit NVARCHAR(50) NOT NULL,
);

CREATE TABLE PROGRESS(
ID INT IDENTITY PRIMARY KEY,
PostID INT FOREIGN KEY REFERENCES Posts(ID),
BeforeWeight INT NOT NULL,
AfterWeight INT NOT NULL,
BeforePictureUri NVARCHAR(255) NOT NULL,
AfterPictureUri NVARCHAR(255) NOT NULL,
BeforeDate DATE NOT NULL,
AfterDate DATE NOT NULL,
);

CREATE TABLE Post_Likes(
PostID INT NOT NULL FOREIGN KEY REFERENCES Posts(ID),
UserID INT NOT NULL FOREIGN KEY REFERENCES Users(ID),
CONSTRAINT PK_Post_Likes PRIMARY KEY(PostID, UserID),
CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE Comments(
ID INT IDENTITY PRIMARY KEY,
PostID INT FOREIGN KEY REFERENCES Posts(ID),
AuthorID INT FOREIGN KEY REFERENCES Users(ID),
ParentID INT FOREIGN KEY REFERENCES Comments(ID) DEFAULT NULL,
Body NVARCHAR(MAX) NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE Post_Shares(
PostID INT FOREIGN KEY REFERENCES Posts(ID),
UserID INT FOREIGN KEY REFERENCES Users(ID),
CONSTRAINT PK_Post_Shares PRIMARY KEY(PostID, UserID),
CreatedAt DATETIME DEFAULT GETDATE(),
);

CREATE TABLE FriendRequests(
SenderID INT REFERENCES Users(ID),
ReceiverID INT REFERENCES Users(ID),
CreatedAt DATETIME DEFAULT GETDATE(),
CONSTRAINT PK_FriendRequests PRIMARY KEY(SenderID, ReceiverID),
);

CREATE TABLE Friends(
SenderID INT REFERENCES Users(ID),
ReceiverID INT REFERENCES Users(ID),
CreatedAt DATETIME DEFAULT GETDATE(),
CONSTRAINT PK_Friends PRIMARY KEY(SenderID, ReceiverID),
);

CREATE TABLE Chat(
ID INT IDENTITY PRIMARY KEY,
User1ID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
User2ID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);
CREATE TABLE ChatMessages(
ID INT IDENTITY PRIMARY KEY,
ChatID INT FOREIGN KEY REFERENCES Chat(ID) NOT NULL,
AuthorID INT FOREIGN KEY REFERENCES Users(ID) NOT NULL,
Body NVARCHAR(MAX) NOT NULL,
CreatedAt DATETIME DEFAULT GETDATE(),
);



