CREATE OR ALTER PROCEDURE usp_Chat_InsertChat
	@User1ID INT,
	@User2ID INT
	AS
	BEGIN
	IF NOT EXISTS (SELECT * FROM CHAT WHERE (User1ID = @User1ID AND User2ID = @User2ID) OR (User1ID = @User2ID AND User2ID = @User1ID))
		INSERT INTO CHAT (User1ID, User2ID) VALUES (@User1ID, @User2ID)
	END
